### ISSUE TITLE
Not able to migrate

### ISSUE THREAD

**Issue by shivani881** [kmranrg/Telusko#9]
![image](https://user-images.githubusercontent.com/87324312/191660981-02d4d4cf-8241-4373-8ae0-f5a4aaf2a76a.png)

![image](https://user-images.githubusercontent.com/87324312/191661026-6125b0cb-c07b-48f5-9c27-6495e200e45a.png)

this is the error, i am not able to solve

**Comment by kmranrg** [comment]
Hello Shivani,

Sorry to hear that the code isn't working for you. Please perform the following troubleshooting steps:

  1.  Update the Django to the latest version in your system
  2.  Make sure latest version of Python3 is running in your system
  3.  Try not to download the code instead use the command 'git clone https://github.com/kmranrg/TravelWorld' in cmd

Perform these steps and let me know if that works or not.

Thanks & Regards,
Kumar Anurag
________________________________
From: shivani ***@***.***>
Sent: 22 September 2022 10:21 AM
To: kmranrg/TravelWorld ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kmranrg/TravelWorld] Not able to migrate (Issue #9)


[image]<https://user-images.githubusercontent.com/87324312/191660981-02d4d4cf-8241-4373-8ae0-f5a4aaf2a76a.png>

[image]<https://user-images.githubusercontent.com/87324312/191661026-6125b0cb-c07b-48f5-9c27-6495e200e45a.png>

this is the error, i am not able to solve

**Comment by shivani881** [comment]
Hey Anurag,

I did what you suggested but still facing the same problem, can you please create a new virtual env and clone your project and try to run then notify me.

Thank you
Shivani

**Comment by kmranrg** [comment]
Hello Shivani,

First of all, thanks for going through the recommended steps!

After doing the error analysis from the screenshot you've attached, I found out that there's a blockage in port 5432 due to some 3rd party application. It may be due to the Windows Firewall or some other application.

<img width="1094" alt="Screenshot 2022-09-28 at 10 34 38 AM" src="https://user-images.githubusercontent.com/31153544/192694531-134c1cc9-9f7d-4d08-9f99-e63cd5e0dfc8.png">

For sorting out this issue, I am giving you the official troubleshooting steps recommended by the Django community. So, please follow the link below.

Troubleshooting Steps - click here<https://django.fun/en/qa/427033/>

Perform the troubleshooting and let me know the status.

Note: As I can see, you're using Windows 11 OS, so the link I've given is specifically covering that same OS.

----------------------------------------------
Thanks & Regards,
Kumar Anurag
CEO & Found​er of SmartGurucool
________________________________

**Comment by kmranrg** [comment]
++ Attaching your specific portion of error screenshot

----------------------------------------------
Thanks & Regards,
Kumar Anurag
CEO & Found​er of SmartGurucool
________________________________

**Comment by shivani881** [comment]
Hi Anurag,
I tried what you suggested  but now its showing this.
![image](https://user-images.githubusercontent.com/87324312/192762282-7d86b036-c25a-4cc5-8a73-47c61a4a5036.png)
One more thing i am not able to understand is i didn't setup postgresql with your project. I just clone, and run pip freeze > requirements.txt and pip install -r requirements.txt and then migrate command, so is these all steps what i need to do to run your project.

**Comment by kmranrg** [comment]
Hello Shivani,

Let me know about your availability so that we can schedule a troubleshooting session for this. We will be performing the following steps in the meeting:

  1.  Installing the Postgres and enabling it in the background
  2.  We will go to telusko\settings.py in the project folder
  3.  Around line 78, there's DATABASES dictionary, we will set the value for keys ('NAME', 'USER' & 'PASSWORD') to 'postgres'
  4.  Then we'll execute `python3 manage.py makemigrations` & `python3 manage.py migrate`
  5.  Finally, we will run the project by `python3 manage.py runserver`

.....................................................................................
Thanks & Regards,
Kumar Anurag
CEO & Found​er of SmartGurucool
________________________________

**Comment by shivani881** [comment]
Hi Anurag

Thanks for the help, Project is running now.
Btw Didn't you do testing of this application?



Regards
shivani

**Comment by kmranrg** [comment]
Hello Shivani,

I'm glad that the project is now working for you!

Actually, I created this project two years ago so at that time this project was running good. But in 2 years, there's lot of updates happened in modules/libraries that I've used. So, because of that we needed to change few things like Postgres. I remember at that time, I never used Postgres in this project.

Once again, special thanks to you that I got a chance to update this project.

.......................................................................
Thanks & Regards,
Kumar Anurag
CEO & Found​er of SmartGurucool
________________________________
